### ISSUE TITLE
setODR mask bits

### ISSUE THREAD

**Issue by rick-conrad** [sparkfun/SparkFun_MMA8452Q_Arduino_Library#1]
In the setODR routine;
ctrl &= 0xC**F**; // Mask out data rate bits
should be,
ctrl &= 0xC**7**; // Mask out data rate bits

**Comment by jimblom** [comment]
Thanks for the heads up! ODR mask fixed in [commit d8e6527](https://github.com/sparkfun/SparkFun_MMA8452Q_Arduino_Library/commit/d8e6527e6e7c8f6b5ee26131206356df3d5daeec).
