### ISSUE TITLE
ESP8266 Compiling Errors with the Arduino IDE

### ISSUE THREAD

**Issue by bboyho** [sparkfun/SparkFun_MMA8452Q_Arduino_Library#2]
Not a big deal but, the library was designed for the Arduino UNO development board so there can be some issues with libraries if you are trying to port it to another microcontroller. If you see this error output when trying to upload to an ESP8266 through the Arduino IDE, this is due to the fact that the MMA8452Q's library is using a variable that is already used by the ESP8266 core:

```
Arduino: 1.6.4 (Windows 7), Board: "SparkFun ESP8266 Thing, 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from SparkFun_MMA8452Q_Basic.ino:34:0:
C:\Users\bobby.chan\Documents\Arduino\libraries\SparkFun_MMA8452Q/SparkFun_MMA8452Q.h:32:11: error: 'STATUS' redeclared as different kind of symbol
STATUS = 0x00,
       ^
In file included from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697/tools/sdk/include/ets_sys.h:11:0,
             from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/pgmspace.h:9,
             from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/WString.h:29,
             from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/Print.h:26,
             from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/Stream.h:26,
             from C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697\libraries\Wire/Wire.h:28,
             from SparkFun_MMA8452Q_Basic.ino:33:
C:\Users\...\AppData\Roaming\Arduino15\packages\SparkFun\hardware\esp8266\1.6.4-673-g8cd3697/tools/sdk/include/c_types.h:58:3: error: previous declaration of 'typedef enum STATUS STATUS'
 } STATUS;
   ^
Error compiling.
```

Try modifying the MMA8452Q's library by changing the variable name with a text editor by :

changing _STATUS_ to **STATUS_M** in the file _SparkFun_MMA8452Q.cpp_ on line 95 

changing _STATUS_ to **STATUS_M** in the file _SparkFun_MMA8452Q.h_ on line 32 

After changing the variable names, I did not see any issues compiling the code in the Arduino IDE.

**Comment by jimblom** [comment]
Thanks, Bobby! Made the status register definition more unique in [commit 6a4f30b](https://github.com/sparkfun/SparkFun_MMA8452Q_Arduino_Library/commit/6a4f30be4cc908775052af966b2a372c003865fd)
